### ISSUE TITLE
SSH Connections fail due to missing fonts

### ISSUE THREAD

**Issue by drnatewhims** [RamboRogers/cyberpamnow#3]
SSH connection to fedora 

from the logs after failed connection:

guacd[989]: INFO:       Unable to load font "DejaVu Sans Mono"
guacd[989]: ERROR:      Unable to set initial font "DejaVu Sans Mono"
![cyberpam-log](https://github.com/user-attachments/assets/ca20caa4-3f17-441e-a95f-e445e848e336)

**Comment by RamboRogers** [comment]
Working

**Comment by RamboRogers** [comment]
Should be fixed with new v0.1.1c released.
